apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-app
  namespace: argocd
spec:
  project: gitops-demo
  destination:
    namespace: gitops-demo
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Osomudeya/DevOps-Home-Lab-2025.git
    targetRevision: home-lab
    path: gitops-demo/base
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations
