apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: humor-game2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: frontend
          image: humor-game-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: humor-game-config
                  key: API_BASE_URL
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: humor-game-config
                  key: NODE_ENV
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
